apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: backend
data:
  application.yml: |
    server:
      port: 8081

    spring:
      application:
        name: USER-SERVICE

    eureka:
      client:
        serviceUrl:
          defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}