server:
  port: 8081

spring:
  application:
    name: user-service

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server.backend:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: false
#    hostname: user-service.backend

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
